//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAC.UServe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAC_UserInfo", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class UAC_UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Is_AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Needs_ResetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SQLResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Is_Admin {
            get {
                return this.Is_AdminField;
            }
            set {
                if ((this.Is_AdminField.Equals(value) != true)) {
                    this.Is_AdminField = value;
                    this.RaisePropertyChanged("Is_Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Needs_Reset {
            get {
                return this.Needs_ResetField;
            }
            set {
                if ((this.Needs_ResetField.Equals(value) != true)) {
                    this.Needs_ResetField = value;
                    this.RaisePropertyChanged("Needs_Reset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SQLResult {
            get {
                return this.SQLResultField;
            }
            set {
                if ((object.ReferenceEquals(this.SQLResultField, value) != true)) {
                    this.SQLResultField = value;
                    this.RaisePropertyChanged("SQLResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAC_OnlineList", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class UAC_OnlineList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] UList {
            get {
                return this.UListField;
            }
            set {
                if ((object.ReferenceEquals(this.UListField, value) != true)) {
                    this.UListField = value;
                    this.RaisePropertyChanged("UList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAC_Bytes", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class UAC_Bytes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SystemDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SystemData {
            get {
                return this.SystemDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemDataField, value) != true)) {
                    this.SystemDataField = value;
                    this.RaisePropertyChanged("SystemData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UAC_SSList", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class UAC_SSList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SSDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SSIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SSDate {
            get {
                return this.SSDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SSDateField, value) != true)) {
                    this.SSDateField = value;
                    this.RaisePropertyChanged("SSDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SSId {
            get {
                return this.SSIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SSIdField, value) != true)) {
                    this.SSIdField = value;
                    this.RaisePropertyChanged("SSId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UServe.uService")]
    public interface uService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_EnterLogin", ReplyAction="http://tempuri.org/uService/UAC_EnterLoginResponse")]
        UAC.UServe.UAC_UserInfo UAC_EnterLogin(UAC.UServe.UAC_UserInfo login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_EnterLogin", ReplyAction="http://tempuri.org/uService/UAC_EnterLoginResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_EnterLoginAsync(UAC.UServe.UAC_UserInfo login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_ChangePassword", ReplyAction="http://tempuri.org/uService/UAC_ChangePasswordResponse")]
        UAC.UServe.UAC_UserInfo UAC_ChangePassword(UAC.UServe.UAC_UserInfo cp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_ChangePassword", ReplyAction="http://tempuri.org/uService/UAC_ChangePasswordResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_ChangePasswordAsync(UAC.UServe.UAC_UserInfo cp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_ForgotPassword", ReplyAction="http://tempuri.org/uService/UAC_ForgotPasswordResponse")]
        UAC.UServe.UAC_UserInfo UAC_ForgotPassword(UAC.UServe.UAC_UserInfo fp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_ForgotPassword", ReplyAction="http://tempuri.org/uService/UAC_ForgotPasswordResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_ForgotPasswordAsync(UAC.UServe.UAC_UserInfo fp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_RetrieveOnlineUsers", ReplyAction="http://tempuri.org/uService/UAC_RetrieveOnlineUsersResponse")]
        UAC.UServe.UAC_OnlineList UAC_RetrieveOnlineUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_RetrieveOnlineUsers", ReplyAction="http://tempuri.org/uService/UAC_RetrieveOnlineUsersResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_OnlineList> UAC_RetrieveOnlineUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_EmailInUse", ReplyAction="http://tempuri.org/uService/UAC_EmailInUseResponse")]
        UAC.UServe.UAC_UserInfo UAC_EmailInUse(UAC.UServe.UAC_UserInfo eiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_EmailInUse", ReplyAction="http://tempuri.org/uService/UAC_EmailInUseResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_EmailInUseAsync(UAC.UServe.UAC_UserInfo eiu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_ImOnline", ReplyAction="http://tempuri.org/uService/UAC_ImOnlineResponse")]
        UAC.UServe.UAC_UserInfo UAC_ImOnline(UAC.UServe.UAC_UserInfo imo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_ImOnline", ReplyAction="http://tempuri.org/uService/UAC_ImOnlineResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_ImOnlineAsync(UAC.UServe.UAC_UserInfo imo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_PlayerList", ReplyAction="http://tempuri.org/uService/UAC_PlayerListResponse")]
        UAC.UServe.UAC_OnlineList UAC_PlayerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_PlayerList", ReplyAction="http://tempuri.org/uService/UAC_PlayerListResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_OnlineList> UAC_PlayerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_CreateAccount", ReplyAction="http://tempuri.org/uService/UAC_CreateAccountResponse")]
        UAC.UServe.UAC_UserInfo UAC_CreateAccount(UAC.UServe.UAC_UserInfo ca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_CreateAccount", ReplyAction="http://tempuri.org/uService/UAC_CreateAccountResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_CreateAccountAsync(UAC.UServe.UAC_UserInfo ca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_UploadSS", ReplyAction="http://tempuri.org/uService/UAC_UploadSSResponse")]
        bool UAC_UploadSS(UAC.UServe.UAC_Bytes ub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_UploadSS", ReplyAction="http://tempuri.org/uService/UAC_UploadSSResponse")]
        System.Threading.Tasks.Task<bool> UAC_UploadSSAsync(UAC.UServe.UAC_Bytes ub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_LoadSSList", ReplyAction="http://tempuri.org/uService/UAC_LoadSSListResponse")]
        UAC.UServe.UAC_SSList UAC_LoadSSList(string username, bool admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_LoadSSList", ReplyAction="http://tempuri.org/uService/UAC_LoadSSListResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_SSList> UAC_LoadSSListAsync(string username, bool admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_GetSS", ReplyAction="http://tempuri.org/uService/UAC_GetSSResponse")]
        UAC.UServe.UAC_Bytes UAC_GetSS(int record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_GetSS", ReplyAction="http://tempuri.org/uService/UAC_GetSSResponse")]
        System.Threading.Tasks.Task<UAC.UServe.UAC_Bytes> UAC_GetSSAsync(int record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_DeleteSS", ReplyAction="http://tempuri.org/uService/UAC_DeleteSSResponse")]
        bool UAC_DeleteSS(int record, string guid, int user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/uService/UAC_DeleteSS", ReplyAction="http://tempuri.org/uService/UAC_DeleteSSResponse")]
        System.Threading.Tasks.Task<bool> UAC_DeleteSSAsync(int record, string guid, int user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface uServiceChannel : UAC.UServe.uService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class uServiceClient : System.ServiceModel.ClientBase<UAC.UServe.uService>, UAC.UServe.uService {
        
        public uServiceClient() {
        }
        
        public uServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public uServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public uServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public uServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UAC.UServe.UAC_UserInfo UAC_EnterLogin(UAC.UServe.UAC_UserInfo login) {
            return base.Channel.UAC_EnterLogin(login);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_EnterLoginAsync(UAC.UServe.UAC_UserInfo login) {
            return base.Channel.UAC_EnterLoginAsync(login);
        }
        
        public UAC.UServe.UAC_UserInfo UAC_ChangePassword(UAC.UServe.UAC_UserInfo cp) {
            return base.Channel.UAC_ChangePassword(cp);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_ChangePasswordAsync(UAC.UServe.UAC_UserInfo cp) {
            return base.Channel.UAC_ChangePasswordAsync(cp);
        }
        
        public UAC.UServe.UAC_UserInfo UAC_ForgotPassword(UAC.UServe.UAC_UserInfo fp) {
            return base.Channel.UAC_ForgotPassword(fp);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_ForgotPasswordAsync(UAC.UServe.UAC_UserInfo fp) {
            return base.Channel.UAC_ForgotPasswordAsync(fp);
        }
        
        public UAC.UServe.UAC_OnlineList UAC_RetrieveOnlineUsers() {
            return base.Channel.UAC_RetrieveOnlineUsers();
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_OnlineList> UAC_RetrieveOnlineUsersAsync() {
            return base.Channel.UAC_RetrieveOnlineUsersAsync();
        }
        
        public UAC.UServe.UAC_UserInfo UAC_EmailInUse(UAC.UServe.UAC_UserInfo eiu) {
            return base.Channel.UAC_EmailInUse(eiu);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_EmailInUseAsync(UAC.UServe.UAC_UserInfo eiu) {
            return base.Channel.UAC_EmailInUseAsync(eiu);
        }
        
        public UAC.UServe.UAC_UserInfo UAC_ImOnline(UAC.UServe.UAC_UserInfo imo) {
            return base.Channel.UAC_ImOnline(imo);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_ImOnlineAsync(UAC.UServe.UAC_UserInfo imo) {
            return base.Channel.UAC_ImOnlineAsync(imo);
        }
        
        public UAC.UServe.UAC_OnlineList UAC_PlayerList() {
            return base.Channel.UAC_PlayerList();
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_OnlineList> UAC_PlayerListAsync() {
            return base.Channel.UAC_PlayerListAsync();
        }
        
        public UAC.UServe.UAC_UserInfo UAC_CreateAccount(UAC.UServe.UAC_UserInfo ca) {
            return base.Channel.UAC_CreateAccount(ca);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_UserInfo> UAC_CreateAccountAsync(UAC.UServe.UAC_UserInfo ca) {
            return base.Channel.UAC_CreateAccountAsync(ca);
        }
        
        public bool UAC_UploadSS(UAC.UServe.UAC_Bytes ub) {
            return base.Channel.UAC_UploadSS(ub);
        }
        
        public System.Threading.Tasks.Task<bool> UAC_UploadSSAsync(UAC.UServe.UAC_Bytes ub) {
            return base.Channel.UAC_UploadSSAsync(ub);
        }
        
        public UAC.UServe.UAC_SSList UAC_LoadSSList(string username, bool admin) {
            return base.Channel.UAC_LoadSSList(username, admin);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_SSList> UAC_LoadSSListAsync(string username, bool admin) {
            return base.Channel.UAC_LoadSSListAsync(username, admin);
        }
        
        public UAC.UServe.UAC_Bytes UAC_GetSS(int record) {
            return base.Channel.UAC_GetSS(record);
        }
        
        public System.Threading.Tasks.Task<UAC.UServe.UAC_Bytes> UAC_GetSSAsync(int record) {
            return base.Channel.UAC_GetSSAsync(record);
        }
        
        public bool UAC_DeleteSS(int record, string guid, int user) {
            return base.Channel.UAC_DeleteSS(record, guid, user);
        }
        
        public System.Threading.Tasks.Task<bool> UAC_DeleteSSAsync(int record, string guid, int user) {
            return base.Channel.UAC_DeleteSSAsync(record, guid, user);
        }
    }
}
